version: 2
updates:
  - package-ecosystem: "pip" # Για Python πακέτα (requirements.txt)
    directory: "/" # Ο φάκελος όπου βρίσκεται το requirements.txt
    schedule:
      interval: "weekly" # Έλεγχος κάθε εβδομάδα
    open-pull-requests-limit: 5 # Μέχρι 5 αυτόματα updates ταυτόχρονα
